import { Beneficiary, Facility, ReferralTimelineStep } from '../types';

export const INITIAL_BENEFICIARY: Beneficiary = {
  id: 'BEN-2026-0941',
  name: 'Sunita Patil',
  nameHindi: 'सुनीता पाटिल',
  nameMarathi: 'सुनीता पाटील',
  age: 28,
  gender: 'Female',
  village: 'Karajgaon (Ward 3)',
  subCenter: 'Sub-Center 04',
  abhaId: '91-4029-8472-1029',
  rchId: '2714-9821-0045',
  gestationalAge: '34 Wks 3 D',
  gravida: 2,
  lmpDate: '02 March 2026',
  eddDate: '07 Dec 2026',
  riskStatus: 'NORMAL',
  riskTitle: 'Antenatal Health Assessment',
  riskTitleHindi: 'गर्भावस्था स्वास्थ्य मूल्यांकन',
  riskTitleMarathi: 'प्रसूतीपूर्व आरोग्य तपासणी (ANC)',
  husbandName: 'Ramesh Patil',
  husbandPhone: '+91 98234 56789',
  ashaWorker: 'Savita Bai (संगीता ताई)',
  photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
  proteinuria: '++ (Dipstick)',
  vitals: {
    systolic: 155,
    diastolic: 100,
    temperature: 99.2,
    tempUnit: 'F',
    pulseRate: 88,
    spo2: 97,
    bodyWeight: 58.5,
    randomBloodSugar: 110,
    recordedAt: 'Today, 10:15 AM'
  }
};

export const FACILITIES: Facility[] = [
  {
    id: 'phc-belora',
    name: 'PHC Belora (प्राथमिक आरोग्य केंद्र)',
    nameHindi: 'प्राथमिक आरोग्य केंद्र बेलोरा',
    distanceKm: 4.2,
    travelTimeMins: 12,
    type: 'Primary Health Centre',
    doctorName: 'Dr. Anita Sharma (MBBS, MO)',
    doctorRole: 'Medical Officer on Active Triage',
    doctorPhoto: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=300&q=80',
    isOnDuty: true,
    tags: ['Emergency Stabilization', 'Maternity Ward (12 Beds)', '24x7 Lab Diagnostics']
  },
  {
    id: 'dh-wardha',
    name: 'District Civil Hospital, Wardha',
    nameHindi: 'जिला सामान्य रुग्णालय, वर्धा',
    distanceKm: 28,
    travelTimeMins: 48,
    type: 'Secondary Hub',
    doctorName: 'Dr. R. K. Deshpande (MD, Gynae)',
    doctorRole: 'Head of Obstetrics & Gynaecology',
    doctorPhoto: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80',
    isOnDuty: true,
    tags: ['24x7 Blood Bank', 'ICU & C-Section OT', 'Maternal Health Unit']
  }
];

export const INITIAL_TIMELINE_STEPS: ReferralTimelineStep[] = [
  {
    stepNumber: 1,
    title: 'Step 1: Referral Generated by ASHA',
    time: '10:30 AM',
    status: 'completed',
    description: 'Created by ASHA Savita Bai (Sub-Center Khairi). Vitals & symptom telemetry uploaded.'
  },
  {
    stepNumber: 2,
    title: 'Step 2: Accepted by PHC Belora',
    time: '10:45 AM',
    status: 'completed',
    description: 'Reviewed & bed reserved by Dr. Anita Sharma. Emergency intake team on standby.'
  },
  {
    stepNumber: 3,
    title: 'Step 3: In Transit / Arriving',
    time: 'ETA ~8m',
    status: 'active',
    badge: 'ACTIVE',
    description: '108 Ambulance MH-31-AZ-4412 carrying beneficiary. Accompanying person: Husband (Ramesh).',
    actions: [
      { label: 'Confirm Arrival at PHC', action: 'confirm_arrival', variant: 'primary' },
      { label: 'Call Driver', action: 'call_driver', variant: 'secondary' }
    ]
  },
  {
    stepNumber: 4,
    title: 'Step 4: Clinical Treatment & Stabilization',
    status: 'pending',
    badge: 'Pending',
    description: 'IV Magnesium sulfate, anti-hypertensive protocol, and continuous fetal heart monitoring.'
  },
  {
    stepNumber: 5,
    title: 'Step 5: Discharge & Reverse ASHA Counter-Referral',
    status: 'pending',
    badge: 'Pending',
    description: 'Post-stabilization discharge summary & domiciliary care checklist transmitted back to ASHA app.'
  }
];

export const OTHER_BENEFICIARIES: Beneficiary[] = [
  {
    id: 'BEN-2026-0812',
    name: 'Pooja Sanjay Waghmare',
    nameHindi: 'पूजा संजय वाघमारे',
    nameMarathi: 'पूजा संजय वाघमारे',
    age: 24,
    gender: 'Female',
    village: 'Khairi (Ward 1)',
    subCenter: 'Sub-Center 02',
    abhaId: '91-8201-3341-9921',
    rchId: '2714-8841-0023',
    gestationalAge: '24 Wks 1 D',
    gravida: 1,
    lmpDate: '15 April 2026',
    eddDate: '20 Jan 2027',
    riskStatus: 'NORMAL',
    riskTitle: 'Routine Antenatal Care',
    riskTitleHindi: 'नियमित गर्भावस्था देखभाल',
    riskTitleMarathi: 'नियमित प्रसूतीपूर्व तपासणी (ANC)',
    husbandName: 'Sanjay Waghmare',
    husbandPhone: '+91 98451 22345',
    ashaWorker: 'Savita Bai',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    proteinuria: 'Nil',
    vitals: {
      systolic: 118,
      diastolic: 76,
      temperature: 98.4,
      tempUnit: 'F',
      pulseRate: 74,
      spo2: 99,
      bodyWeight: 52.0,
      randomBloodSugar: 92,
      recordedAt: '03 Sep 2026'
    }
  },
  {
    id: 'BEN-2026-0733',
    name: 'Kavita Rajesh Shinde',
    nameHindi: 'कविता राजेश शिंदे',
    nameMarathi: 'कविता राजेश शिंदे',
    age: 31,
    gender: 'Female',
    village: 'Belora (Ward 2)',
    subCenter: 'Sub-Center 04',
    abhaId: '91-1029-4482-6612',
    rchId: '2714-7712-0091',
    gestationalAge: '30 Wks 5 D',
    gravida: 3,
    lmpDate: '28 Feb 2026',
    eddDate: '05 Dec 2026',
    riskStatus: 'NORMAL',
    riskTitle: 'Routine Antenatal Care',
    riskTitleHindi: 'नियमित गर्भावस्था देखभाल',
    riskTitleMarathi: 'नियमित प्रसूतीपूर्व तपासणी (ANC)',
    husbandName: 'Rajesh Shinde',
    husbandPhone: '+91 97632 11984',
    ashaWorker: 'Savita Bai',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    proteinuria: 'Trace',
    vitals: {
      systolic: 124,
      diastolic: 82,
      temperature: 98.6,
      tempUnit: 'F',
      pulseRate: 80,
      spo2: 98,
      bodyWeight: 49.2,
      randomBloodSugar: 104,
      recordedAt: '02 Sep 2026'
    }
  }
];
